### ISSUE TITLE
Theme types

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#11]
There are different kinds of themes:
- Themes based on a BuildingCollection (e.g. "European Buildings" gameobject)
- Themes based on a fixed list of building names (configurable)

How can we solve this?

**Comment by earalov** [comment]
In the end all themes for districts will be stored as sets of buildings names no matter where these names come from (see my latest PR). Vanilla themes are just for convenience of testing and for those users who don't use custom growables. When Building Themes Manager UI is ready, user will be able to create his themes of both custom and vanilla buildings. And the source for BTMUI's buildings list will be PrefabCollection<BuildingInfo>.

**Comment by bloodypenguin** [comment]
Implemented merging of loaded and built-in themes
