### ISSUE TITLE
Rename "International" to "American"

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#17]
I think that makes more sense. Architecture in Asia, Africa etc. looks quite different.

**Comment by bloodypenguin** [comment]
I would prefer to stick to 'International'. This is what Deluxe Edition artbook says:

> Cities: Skylines was designed to be a modern city builder and the architecture
> was inspired by contemporary designs all across the globe, but with focus on
> the growing economies where new cities seems to pop up every day.
> The timeline shifts from the end of the 20th century, into our own time
> and slightly in the future. The style takes inspiration from Western Suburbia,
> Asian city centers and Middle Eastern skyscrapers but ties it together into an
> eclectic blend of modern cityscape.

And most level 5/3 buildings (especially that 4x4 [yellowish Office building](http://screencast.com/t/IIfkOmLW9SeN)) look definitely non-American.  Also there is an architectural style, called ['International'](https://en.wikipedia.org/wiki/International_Style_%28architecture%29) - an that's exactly how those non-euro buildings look like.

**Comment by boformer** [comment]
ok
