### ISSUE TITLE
Extending the vanilla themes

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#18]
I thought about it again: It makes sense to allow users to add their own buildings to euro/int theme (by adding them to the config).

It is the easiest way to use custom assets with this mod.

For example, users could add these buildings to the european theme:
http://steamcommunity.com/sharedfiles/filedetails/?id=446190120
http://steamcommunity.com/sharedfiles/filedetails/?id=446201704

And all of these to the international theme:
http://steamcommunity.com/sharedfiles/filedetails/?id=423659623

To make it futureproof, vanilla buildings should be never be saved in the config (`isBuiltIn` field for `Configuration.Building`)

**Comment by bloodypenguin** [comment]
Nice idea! This way 'International' and 'European' themes of config will only contain additional custom buildings. But themes should also have `isBuiltIn` flag (as it is now) because vanilla buildings _must_ be saved to config it a theme itself is not built-in.

**Comment by boformer** [comment]
Working on this
