### ISSUE TITLE
First beta release date? What features are we still lacking for it?

### ISSUE THREAD

**Issue by bloodypenguin** [boformer/BuildingThemes#22]
It looks like our core logic works now. I think custom themes may be added later.
At this point I think we might just add a 'Custom' theme as temporary solution that might allow growing of custom buildings alongside with vanilla ones in themed districts.

I'll be mostly unavailable for modding from upcoming Thursday (6/25) till August because I'll marry on the Saturday (6/27) and will have my honeymoon after that. And before that I would like to enjoy seeing this mod released in Workshop :)

**Comment by boformer** [comment]
In 2 hours?

I am testing the extension feature right now. Do you have the time to write a mod description?

**Comment by bloodypenguin** [comment]
I think I do but what about that 'Custom' theme. Without it users will be limited only to vanilla buildings. And if we decide that each theme should apply to a specific zone type, we should do that now too.

**Comment by boformer** [comment]
The problem is, if we add a "custom" theme, we can never remove it again. I would release it like it is now (with my PR it is possible to add custom buildings to the themes), and concentrate on the GUI for theme management.

**Comment by bloodypenguin** [comment]
Ok. I will prepare description and cover art. Will add them as pull request.

**Comment by bloodypenguin** [comment]
Pushed these changes straight to master: [commit](https://github.com/boformer/BuildingThemes/commit/2bf1ccfd1fd7c9b776fb028d746e9f85dcad6c7e). Please review the description.
