### ISSUE TITLE
Remove buildings from the vanilla theme.

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#24]
Based on this reddit comment:

> There's one ,just one building I can't handle. it's the european one that's often blue and orange and has a rounded roof. It's pretty realistic, I know, but I generally dislike that direction in architecture, so i tend to manually buldoze it every time it pops up. 

We could extend the config format like this:

``` xml
    <Theme name="European">
      <Buildings>
        <Building name="ugly_vanilla_blueroof_building" include="false" />
      </Buildings>
    </Theme>
```

**Comment by bloodypenguin** [comment]
Yes I thought about that too. That brings back blacklist idea :)

**Comment by bloodypenguin** [comment]
working on it
