### ISSUE TITLE
Adjustable spawn rate?

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#3]
It would be easy to add an adjustable spawn rate. What do you think?

**Comment by bloodypenguin** [comment]
Haven't investigated that yet.

**Comment by boformer** [comment]
There is one fastlist for every "area index" (a unique number that contains the width, depth, level, zone type ...).

The fastlist contains prefab ids. One of it is randomly selected by the getRandomBuildingInfo method.

If we include a certain prefab id 5 times (other ids only one time), the spawn chance will be higher.

By default we could add every prefab id 10 times. The player can change it to a higher or lower value.
