### ISSUE TITLE
Theme Management GUI

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#30]
Proposal:

We manage a list of buildings which are available (Vanilla and Custom assets) as a separate XML file.

When a new building is found that is not in the XML file, a window pops up:

```
New growable asset found: (name)
(rendered preview)
(stats)

Add the asset to themes:
[ X ] European
[   ] International
[   ] Custom theme
[   ] Another custom theme
[ + New Theme ]

[ Done ]
```

The mod also adds a new entry to the Esc menu: "Theme Manager"

It opens a window with 3 columns:

left column (width 25%):
The left column contains the list of themes (and a Add new theme button in the bottom). The user has to select one.

Center column (width 50%):
The list of all growables with checkboxes to enable an asset in a theme. The list should also contain assets which are not loaded, but were found in the XML buildings list. It would be nice if we could display a more readable name (load title from workshop, replace "_" with " ")

Right column:
Top:
preview and stats of the selected asset

Bottom:
Information about the theme.
For example, display how many assets of each zone type are included.
Display a warning when there is a L2 4x4 asset, but no L1 4x4 asset.

**Comment by boformer** [comment]
The code of ImprovedModsPanel + an inspection of the content manager might be a good starting point.

**Comment by bloodypenguin** [comment]
> ImprovedModsPanel

Improved Assets Panel, of course. We need filtering here too. Also some guy asked me if I could add Steam collections for IAP. I think, that feature might be added to both IAP and Themes Manager UI.

**Comment by bloodypenguin** [comment]
Something like 'Import theme from Steam Collection'. And collection file ID needs to be provided for import.

**Comment by boformer** [comment]
Yep, I also thought about that. Do you also want to sync the steam collection regularly, or just have a one-time import?

**Comment by bloodypenguin** [comment]
I think even one-time import is a challenge enough. It will be fine.

**Comment by bloodypenguin** [comment]
BTW. Thank you very much for the testing you do! I just don't have enough spare time for it.

**Comment by bloodypenguin** [comment]
Hopefully I'll find some spare time today or tomorrow to implement thumbnails generation feature.

**Comment by boformer** [comment]
Look at IPT. They just implemented a vehicle preview.

**Comment by bloodypenguin** [comment]
Checked IPT. Haven't seen any previews. Nothing in its description too. Maybe you meant another mod?

**Comment by boformer** [comment]
Oh right, it says "coming soon": http://www.reddit.com/r/CitiesSkylinesModding/comments/3aqwap/vehicle_preview_in_avo_coming_soon/

**Comment by bloodypenguin** [comment]
> Hovering/changing a color updates the preview.

Looks like it will be 3d preview, like in ModTools. My idea is about taking and caching screenshots and using them as thumbnails.

**Comment by bloodypenguin** [comment]
This should also solve 'Lego blocks' problem for assets that don't provide their own thumbnails. The trick is how to display not only the main mesh but all props too.

**Comment by boformer** [comment]
There we go: https://github.com/SamsamTS/CS-AdvancedVehicleOptions/blob/master/AdvancedVehicleOptions/PreviewRenderer.cs

**Comment by boformer** [comment]
This one also has a very nice GUI:
https://github.com/SamsamTS/CS-MeshInfo/tree/master/MeshInfo

**Comment by bloodypenguin** [comment]
BTW, SamsamTS once asked me about collaborating. Maybe his UI experience may be really helpful for us?

**Comment by boformer** [comment]
Oh yes. Very helpful. Ask him if you want 😊

**Comment by SamsamTS** [comment]
I will try and help soon. As you know I just updated AVO. I need to remake some screenshots and such. Also I want to add previews to Mesh Info too.

**Comment by boformer** [comment]
:+1:

**Comment by SamsamTS** [comment]
I wanted to let you know that I started to work on the UI. It's a humble start but it's a start :wink:

**Comment by boformer** [comment]
Yay. I can add you to the repo so you can create a branch.

Create a pull request for your branch so we can discuss the changes.

I'm also planning to clean up the code of the mod.

**Comment by boformer** [comment]
I will do it when I get home, in about 2h.

**Comment by SamsamTS** [comment]
Sounds good to me.

**Comment by boformer** [comment]
Ok, done.

**Comment by boformer** [comment]
@SamsamTS Clone the cleanup branch: https://github.com/boformer/BuildingThemes/tree/cleanup

I will merge it soon when no problems appear.

**Comment by boformer** [comment]
@SamsanTS Can you upload what you have done so far?

**Comment by SamsamTS** [comment]
Have you merged the clean up yet? I was waiting on that so I can create a branch from master. I could make a branch from clean up i guess.

Also I haven't done much yet (I display the list of themes but that's about it). It's too freaking hot here, I'm having a hard time getting anything done and I try to keep the computer off because of the heat.

**Comment by boformer** [comment]
Where are you from? It's also very hot here in germany ;)

**Comment by SamsamTS** [comment]
Hallo neighbor. I live right next to Germany, in France (Alsace to be more precise). I don't speak German though, sorry.
