### ISSUE TITLE
Refresh RedirectCallsState when doing RedirectionHelper.PatchJumpTo(...)

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#34]
This is not done in DetoursHolder, only on initial startup.

Is this a problem, or is the content always the same?

**Comment by bloodypenguin** [comment]
It should be done only on initial startup. After a method becomes JITed its address won't change.
See [this](http://stackoverflow.com/questions/5589409/c-sharp-jit-compiling-and-net)
