### ISSUE TITLE
Building Level Control

### ISSUE THREAD

**Issue by SamsamTS** [boformer/BuildingThemes#53]
I heard someone say that the Control Building Level Up mod isn't working anymore and won't be updated. I was wondering if we could incorporate a maximum level option in the district options along side the themes options. Something like a combobox (or several for the different zone types) where you can choose the maximum level.

I know it is possible to make a theme that only include buildings up to certain level, but it may be less practical for the user.

Good idea or not?

**Comment by boformer** [comment]
Are You sure that the mod is broken? The code is quite simple and uses the official mod API.

**Comment by boformer** [comment]
If it really is broken, I would suggest that we release a fixed version.

**Comment by SamsamTS** [comment]
Well I haven't tested it myself (I have no time to play the game anymore).

Here have some links, people seems to complain it doesn't work since the 1.1.1 update :
https://www.reddit.com/r/CitiesSkylinesModding/comments/3c4hkd/july_2015_mod_requests/cstmkdi
http://steamcommunity.com/sharedfiles/filedetails/?id=410535198

**Comment by boformer** [comment]
Just tested the mod, works fine.
