### ISSUE TITLE
nullRefException in ZoneBlock.SimulationStep

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#59]
```
Object reference not set to an instance of an object [System.NullReferenceException]

Details:
No details
System.NullReferenceException: Object reference not set to an instance of an object
  at BuildingThemes.Detour.ZoneBlockDetour.SimulationStep (UInt16 blockID) [0x00000] in <filename unknown>:0 
  at ZoneManager.SimulationStepImpl (Int32 subStep) [0x00000] in <filename unknown>:0 
  at SimulationManagerBase`2[Manager,Properties].SimulationStep (Int32 subStep) [0x00000] in <filename unknown>:0 
  at ZoneManager.ISimulationManager.SimulationStep (Int32 subStep) [0x00000] in <filename unknown>:0 
  at SimulationManager.SimulationStep () [0x00000] in <filename unknown>:0 
  at SimulationManager.SimulationThread () [0x00000] in <filename unknown>:0 
```

Description:
- No I did not modify the BuildingThemes.xml manually
- Occurs every few seconds
- I created a new theme using the UI manager and added some buildings to it. There is a global theme "European" enabled
- If I disable the custom theme I created using the UI, the error stops

**Comment by SamsamTS** [comment]
Could prop be null in ZoneBlockDetour at Line 754?

``` c#
foreach (var prop in buildingInfo.m_props)
```

It's the only thing I can see that would throw a NullReferenceException in SimulationStep.

**Comment by boformer** [comment]
Yes, maybe m_props is null in some cases.

**Comment by SamsamTS** [comment]
What I had in mind is that if prop is null then it would throw an exception when you try to access m_position on the next line :

``` c#
biggestPropPosZ = Mathf.Max(biggestPropPosZ, buildingInfo.m_expandFrontYard ? prop.m_position.z : -prop.m_position.z);
```

so maybe you should add a test, it wouldn't hurt.

``` c#
if (prop != null) biggestPropPosZ = Mathf.Max(biggestPropPosZ, buildingInfo.m_expandFrontYard ? prop.m_position.z : -prop.m_position.z);
```

EDIT: But I guess if m_prop is null it would also throw a NullReferenceException

**Comment by boformer** [comment]
I pushed a fix to master. Do you know how to enable line numbers in exceptions? That would be so helpful.

**Comment by SamsamTS** [comment]
The game isn't compiled in debug mode so no line numbers unfortunately. Maybe with a hacked mono VM or something.

**Comment by boformer** [comment]
Nailed it down. This is the issue: ![Image](http://i.imgur.com/GnsPhN2.png)
