### ISSUE TITLE
Building Theme Manager not working

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#63]
This is a common issue:

![Screenshot](http://i.imgur.com/yl7fadN.jpg)

This is one BuildingThemes.xml that causes this issue: http://pastebin.com/index/eJ10t2KT

**Comment by SamsamTS** [comment]
[Bug found](https://github.com/boformer/BuildingThemes/blob/master/BuildingThemes/GUI/BuildingItem.cs#L63). Will be fixed in the next UI update.

**Comment by boformer** [comment]
Fixed in https://github.com/boformer/BuildingThemes/commit/151cbbd16fe17b99718a6e665db8c0ede26338a0
