### ISSUE TITLE
blacklist mode?

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#7]
Sometimes it might be easier to allow only buildings that are not included in a theme.

Right now when you enable one or both default themes (euro, international), custom buildings will not be placed.

Blacklist mode should be selectable per district.

**Comment by bloodypenguin** [comment]
With my latest changes, no active theme for a district means any growable, including custom assets. Its impractical to implement blacklists IMO.

**Comment by boformer** [comment]
Ok, that works.

**Comment by boformer** [comment]
I implemented blacklist mode as it was a heavily requested feature.
