### ISSUE TITLE
Building Themes Feature included in after dark patch - What will we do now?

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#71]
https://forum.paradoxplaza.com/forum/index.php?threads/cities-skylines-after-dark-dev-diary-2-whats-new-with-modding.878916/

Problems I see so far:
- it does not allow cloning
- no vanilla buildings in themes
- you can only select one theme per district

I guess that a lot of referenced game code will be changed by the patch, and the mod will be broken. While this is not a serious problem because the mod does not break the save files, we have to decide what to do next.

I would suggest that we disable the cloning feature in our mod (only remove the option to create new clones in the theme manager) and **warn users with clones in their themes** that the feature will not be supported by the official theme system. 

Many users also reported **problems with the cloning feature**, so disabling it is probably good to improve the stability of the mod.

I would also suggest that we include a **version switch** in our mod, so that it disables itself when the new update is installed (with option to bypass in the options menu).

Ideas for post-update time:
- Make the Theme Manager GUI work with the official theme system (ingame creation of themes with 3d preview = awesome)
- Create a mod that allows you to select multiple themes per district (if possible)
- Create a mod that improves the footprint selection and upgrade system:
  - support for small 1x2 buildings (if not included in the update)
  - splitting and merging on update
  - intelligent calculation of footprints: for example a 4x10 road block would be filled with building with a depth of 2, to have buildings spawning on both sides.
- Find a better way to create building duplicates for different levels (meshes and textures shared between models, so asset creators can publish multiple assets which do not increase memory usage)

**Comment by SamsamTS** [comment]
It looks like their version of the themes, or styles as they call them, will be very limited. I mean seriously, only one style at a time? That's a huge downgrade compared to our version. For the same results, you will need to create a lot more styles. That poor dropdown list will be very long,

They didn't show the style creation either, I bet you'll not be able to create them while in game, it will probably be a tool like the asset editor.

How I see things : we use the new code as a new base, which probably means less detour, more stability, etc... , and improve on it to get to a state close to where the mod is right now.

Good news, the styles will have their own category on the steam workshop, no needs to scan the mods  to find the themes anymore.

**Comment by boformer** [comment]
> They didn't show the style creation either, I bet you'll not be able to create them while in game, it will probably be a tool like the asset editor.

It is show in one of the last screenshots.

**Comment by SamsamTS** [comment]
> It is show in one of the last screenshots.

That's subtle, I had to look twice before I notice the _Add to style_. That's pretty neat (But ingame style editing is better :P).

**Comment by bloodypenguin** [comment]
> you can only select one theme per district

After the update mod should be renamed to 'Multiple styles per district' :)

> How I see things : we use the new code as a new base, which probably means less detour, more stability, etc... , and improve on it to get to a state close to where the mod is right now.

Absolutely agree. Hopefully it will be possible to reuse their new code in the way we need.

**Comment by bloodypenguin** [comment]
> - Make the Theme Manager GUI work with the official theme system (ingame creation of themes with 3d preview = awesome)
> - Create a mod that allows you to select multiple themes per district (if possible)
> - Create a mod that improves the footprint selection and upgrade system: 

Do you suggest that **Building Themes** should be splitted into multiple mods and the original mod should be deprecated? I'm for modularity :)

**Comment by boformer** [comment]
Yes, I suggest that we add a game version detection to the mod, so that it disables itself when the new update is installed.

Then we can see how we re-implement missing features. If possible in multiple mods.

**Comment by bloodypenguin** [comment]
Closed beta test for small group of core modders [will be available soon](https://www.reddit.com/r/CitiesSkylines/comments/3jhbno/developer_diary_3_expanded_city_services/cup7h8t). It's a great news, guys! :)

**Comment by armarayo** [comment]
Oh darn, all this just when I was looking forward to Building Themes update on the notion of:
"+[*] More cloning options: Change the zone type, color variation or density of a building"

The vanilla buildings and especially european buildings could use a little more color variations for variety. I hope this is done to the whatever theme mod(s) are coming next. I just hope we would of had color variation cloning for 1.1.1c too :/

Looking forward for you future work guys :)

**Comment by boformer** [comment]
The beta is a great idea, but I do not have time until Sep 24 :(

@SamamTS, @earalov Do you want to give it a try?

**Comment by boformer** [comment]
@SamsamTS

**Comment by bloodypenguin** [comment]
I've already sent  application email. @SamsamTS, if you want to apply too, see [this Paradox forum post](https://forum.paradoxplaza.com/forum/index.php?threads/modder-asset-creator-beta-application.880149/) for details.
@boformer If you won't have time (and if I get the beta), I'll try to prepare Building Themes for After Dark release. Will you be available to review pull requests?

**Comment by boformer** [comment]
Yes, I will review them. We just need a strategy what we will do with the mod.

It would be perfect If we could just transfer all current themes to the "styles" system. That means (sorted by priority):
- Remove all detours which modify the building simulation
- Convert the themes in the config to temporary styles (which only exist while the city is loaded)
- Find out if there is a way to enable multiple styles at once, without too much hacking
  - If it works: 
    - Activate the styles which correspond to the selected themes in a district
    - Make the themes policy tab work again
  - If it does not work:
    - Only select the style with the most assets in it
- Make the Theme Manager work again

The minimal goal would be: Detect that after dark patch is installed and disable the mod.

**Comment by bloodypenguin** [comment]
@boformer  TotalyMoo asked me to remind you that you need to send him your  beta email ASAP. Will you participate in beta?

**Comment by boformer** [comment]
I created a private repo for the after dark building themes update: https://github.com/boformer/BuildingThemes-AfterDark

i will push the current version of the mod when I'm at home.

**Comment by boformer** [comment]
Please focus on Mod Tools first. I think many modders rely on it.

**Comment by armarayo** [comment]
Building themes is very important too. After Dark has only one style per district :/ so our mixed european and international districts will vanish into thin air if opened without building themes updated. So I'm turning auto patch off.
