### ISSUE TITLE
When no theme is selected, use vanilla getRandomBuildingInfo 

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#8]

**Comment by bloodypenguin** [comment]
I think it's impractical. IMO it's better just not to filter inside detoured `GetRandomBuildingInfo` when no theme selected.

**Comment by boformer** [comment]
Right now I am trying to replace the filter method with a precompiled fastlist for performance reasons (look at my pr).

**Comment by bloodypenguin** [comment]
Added precompiled themes feature. When no buildings in a precompiled district's theme it means that any building will grow in that district.
