### ISSUE TITLE
Hide after dark buildings for players who do not own the DLC

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#83]
We could also auto-generate the list of buildings.

**Comment by EC-O-DE** [comment]
Hmm. keep in mind that the free portion added some 70 new zone growable buildings, so it's not all paid content the new content.

**Comment by boformer** [comment]
That's right. But the free buildings are in a different "collection", so it is easy to separate them.

**Comment by EC-O-DE** [comment]
This mod comes in so handy I really dislike some of the tourism buildings.

**Comment by boformer** [comment]
fixed.
