### ISSUE TITLE
Store the bundled "vanilla" themes in the themes.xml file or not?

### ISSUE THREAD

**Issue by boformer** [boformer/BuildingThemes#9]
If we store the bundled themes in the xml configuration, players can modify the themes to add custom assets.

The problem is that updating the list will be harder when a game update that contains new assets is released.

**Comment by bloodypenguin** [comment]
Bundled assets names can be retrieved from their respective collections GameObjects like, say, 'European Collections/Europe Commercial Low`. Only GameObjects' names will need to be updated If assets are retrieved in such manner.

**Comment by boformer** [comment]
That's a nice idea.

**Comment by bloodypenguin** [comment]
Anyway, we don't need to store 'vanilla' themes in themes xml file

**Comment by bloodypenguin** [comment]
Implemented merging of loaded and built-in themes
